export const navItems = [
  { id: "nav1", href: "/", label: "Home" },
  { id: "nav2", href: "/about-us", label: "About Us" },
  { id: "nav3", href: "/services", label: "Services" },
  { id: "nav4", href: "/projects", label: "Projects" },
  { id: "nav5", href: "/career", label: "Career" },
  { id: "nav6", href: "/news", label: "Media" },
  { id: "nav7", href: "/faqs", label: "FAQ’s" },
  { id: "nav8", href: "/contact-us", label: "Contact Us" },
  { id: "nav9", href: "/vendor/registration", label: "Vendor Registration" },
] as const;

export const services = [
  {
    id: "industrial-and-infrastructure-solutions",
    title: "Industrial and Infrastructure Solutions",
    image: "/uploads/95812df013c70ad9.jpg",
    items: [
      "Water & Power",
      "Oil & Gas",
      "Petrochemicals Plants",
      "Plant Shutdown Works",
      "Annual Maintenance Contracts",
      "Storage Terminals",
      "Infrastructure",
      "Marine",
      "Construction Works",
    ],
  },
  {
    id: "commercial-and-residential-projects",
    title: "Commercial and Residential Projects",
    image: "/uploads/3946ea2441f7c9b5.jpg",
    items: [
      "Machinery & Equipment Installation.",
      "Commercial Building Construction.",
      "HVAC & MEP Installations",
      "Fire Alarm",
      "Security Systems.",
    ],
  },
  {
    id: "turnkey-projects",
    title: "Turnkey Projects",
    image: "/uploads/f0da0274447e8d79.jpg",
    items: [
      "Erection and commissioning.",
      "Foundation for heavy Equipment, framed structures.",
      "Installation and Erection.",
      "Scaffolding.",
      "Insulation Sand Blasting.",
      "Painting works.",
      "Fire Fighting Systems.",
    ],
  },
  {
    id: "installation-and-maintenance-services",
    title: "Installation and Maintenance Services",
    image: "/uploads/39c64cbb3197c530.jpg",
    items: [
      "NDT Services.",
      "Pump Installation Services.",
      "Water & Sewer Line Works.",
      "Complete Fuel Station Installation (Mechanical & Electrical)",
      "Agricultural & Irrigation system.",
      "Elevator & Escalator Supply, Installation and Maintenance.",
    ],
  },
  {
    id: "civil-construction-services",
    title: "Civil Construction Services",
    image: "/uploads/ee987a1523d6cb86.jpg",
    items: [
      "Construction services",
      "Heavy civil construction & infrastructure.",
      "General contracting.",
      "commercial and industrial facilities construction",
      "Site improvement & utilities projects and rehabilitation.",
      "Railroad construction.",
    ],
  },
  {
    id: "field-services",
    title: "Field Services",
    image: "/uploads/0e504da2ac67094e.jpg",
    items: [
      "Electrical & telecommunications.",
      "Installation of control panels, power supply of receptacles.",
      "Ultra-Filtration System.",
      "MV & LV Control System.",
      "Installation of Power StationsAll panel boards.",
      "Generator Repairs & Maintenances",
    ],
  },
] as const;
